### ISSUE TITLE
cat < ls.txt 1>out.txt 2>error.txt

### ISSUE THREAD

**Issue by dxe58709** [RTFM42/minishell_v2#3]
1> 　標準出力　（cat > out.txt と cat 1> out.txt は同じ意味）
2>　標準エラー出力
<img width="611" alt="スクリーンショット 2024-06-19 14 25 30" src="https://github.com/RTFM42/minishell_v2/assets/133973097/12c2f92c-da48-4e89-b2a4-375a7c91aa2c">

**Comment by seyukun** [comment]
これはやる必要があるか稟議が必要かも

**Comment by seyukun** [comment]
@dxe58709 https://discord.com/channels/1174027148533714994/1238396745361129493/1252870392297816106
