### ISSUE TITLE
SEGV ；cat << EOF

### ISSUE THREAD

**Issue by dxe58709** [RTFM42/minishell_v2#4]
・cat << EOFを途中で終了したとき

<img width="771" alt="スクリーンショット 2024-06-19 14 40 30" src="https://github.com/RTFM42/minishell_v2/assets/133973097/62925902-3747-4c50-86fd-827b91f81c90">

**Comment by seyukun** [comment]
# Fixed
[![FIXED](https://opengraph.githubassets.com/2892419088d30557b6a67c385bf9ab93f42ebf1eed8ea0c5e6e403ff0be19228/RTFM42/minishell_v2/commit/29b70ba573f838fd007b71beb0f6d3a7c06b309a)](https://github.com/RTFM42/minishell_v2/commit/29b70ba573f838fd007b71beb0f6d3a7c06b309a)
