### ISSUE TITLE
SEGV; memory leak at node_add_output

### ISSUE THREAD

**Issue by dxe58709** [RTFM42/minishell_v2#5]
・ls | cat > cat.txt
<img width="930" alt="スクリーンショット 2024-06-21 22 54 29" src="https://github.com/RTFM42/minishell_v2/assets/133973097/a9d25551-0eab-48cf-a6ee-3c8c8608e191">

・echo "Test" | cat > testfile
<img width="928" alt="スクリーンショット 2024-06-21 23 14 23" src="https://github.com/RTFM42/minishell_v2/assets/133973097/8f815a72-efc8-496a-8238-bccf9159a788">

・echo "Hello" > file1
<img width="934" alt="スクリーンショット 2024-06-21 23 20 59" src="https://github.com/RTFM42/minishell_v2/assets/133973097/c229f256-e6a2-4d6d-8fa4-c11986d28a5f">

**Comment by seyukun** [comment]
Fixed
